### ISSUE TITLE
org.pitest.util.PitError: zip END header not found

### ISSUE THREAD

**Issue by ydbondt** [mjedynak/pit-idea-plugin#43]
**Version:** 1.4.4
**OS:**: Ubuntu 20.04 LTS

When running "Pitests using tests in ..." from the projects tab I am getting following error:
(Don't know how to enable verbose logging for PIT plugin, so here's the logging I do have)

```
10:06:49 AM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
Exception in thread "main" org.pitest.util.PitError: zip END header not found (/home/ydbondt/.gradle/caches/modules-2/files-2.1/javax.media/jai/1.1.4+7-lcd/dd65d8d684b320ac41aeb58fa6058449cd8e073d/jai-1.1.4+7-lcd.pom)

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Ubuntu
Version : 11.0.8+10-post-Ubuntu-0ubuntu120.04
Uptime : 391
Input -> 
 1 : -javaagent:/snap/intellij-idea-ultimate/245/lib/idea_rt.jar=40377:/snap/intellij-idea-ultimate/245/bin
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:25)
	at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:117)
	at org.pitest.classpath.ArchiveClassPathRoot.classNames(ArchiveClassPathRoot.java:87)
	at org.pitest.classpath.NameCachingRoot.classNames(NameCachingRoot.java:51)
	at org.pitest.classpath.CompoundClassPathRoot.classNames(CompoundClassPathRoot.java:40)
	at org.pitest.classpath.ClassPath.classNames(ClassPath.java:63)
	at org.pitest.classpath.ClassPath.findClasses(ClassPath.java:147)
	at org.pitest.classpath.ProjectClassPaths.code(ProjectClassPaths.java:39)
	at org.pitest.classpath.CodeSource.getCode(CodeSource.java:41)
	at org.pitest.mutationtest.verify.DefaultBuildVerifier.verify(DefaultBuildVerifier.java:32)
	at org.pitest.mutationtest.tooling.MutationCoverage.verifyBuildSuitableForMutationTesting(MutationCoverage.java:223)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:111)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:121)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:51)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1462)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:115)
	... 14 more
```

**Comment by SimonIT** [comment]
Hi, I have the same problem with version 1.4.5:
```
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 11.0.3-ojdkbuild+7-LTS
Uptime : 1490
Input -> 
 1 : -javaagent:C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7142.45\lib\idea_rt.jar=54956:C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7142.45\bin
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:25)
	at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:117)
	at org.pitest.classpath.ArchiveClassPathRoot.classNames(ArchiveClassPathRoot.java:87)
	at org.pitest.classpath.NameCachingRoot.classNames(NameCachingRoot.java:51)
	at org.pitest.classpath.CompoundClassPathRoot.classNames(CompoundClassPathRoot.java:39)
	at org.pitest.classpath.ClassPath.classNames(ClassPath.java:63)
	at org.pitest.classpath.ClassPath.findClasses(ClassPath.java:143)
	at org.pitest.classpath.ProjectClassPaths.code(ProjectClassPaths.java:39)
	at org.pitest.classpath.CodeSource.getCode(CodeSource.java:41)
	at org.pitest.mutationtest.verify.DefaultBuildVerifier.verify(DefaultBuildVerifier.java:32)
	at org.pitest.mutationtest.tooling.MutationCoverage.verifyBuildSuitableForMutationTesting(MutationCoverage.java:223)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:111)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:121)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.pitest.classpath.ArchiveClassPathRoot.getRoot(ArchiveClassPathRoot.java:115)
	... 14 more

Process finished with exit code 1
```
Some reproduce steps:
1. Clone https://github.com/libgdx/libgdx.git
2. Import as gradle project (Important, there are also maven pom files!)
3. Run `gradlew fetchNatives` (I'm not sure whether this step is necessary)
4. Try to run any of the tests in the module gdx > test, none of them work
