### ISSUE TITLE
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally! (UNKNOWN_ERROR)

### ISSUE THREAD

**Issue by bensnows** [mjedynak/pit-idea-plugin#62]
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally! (UNKNOWN_ERROR)

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : OpenLogic-OpenJDK
Version : 25.412-b08
Uptime : 869
Input -> 
 1 : -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=64130:/Applications/IntelliJ IDEA.app/Contents/bin
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : true

**Comment by 111sebi111** [comment]
3:58:11 PM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
3:58:12 PM PIT >> INFO : Created 1 mutation test units in pre scan
3:58:12 PM PIT >> INFO : Sending 1 test classes to minion
3:58:12 PM PIT >> INFO : Sent tests to minion
3:58:12 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally! (UNKNOWN_ERROR)

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Amazon.com Inc.
Version : 11.0.26+4-LTS
Uptime : 1189
Input -> 
 1 : -javaagent:D:\Apps\IntelliJ IDEA Community Edition 2024.3.5\lib\idea_rt.jar=56771
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Amazon.com Inc.
Version : 11.0.26+4-LTS
Uptime : 1189
Input -> 
 1 : -javaagent:D:\Apps\IntelliJ IDEA Community Edition 2024.3.5\lib\idea_rt.jar=56771
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:118)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:53)
	at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:136)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:136)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:63)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally! (UNKNOWN_ERROR)

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Amazon.com Inc.
Version : 11.0.26+4-LTS
Uptime : 1189
Input -> 
 1 : -javaagent:D:\Apps\IntelliJ IDEA Community Edition 2024.3.5\lib\idea_rt.jar=56771
 2 : -Dfile.encoding=UTF-8
BootClassPathSupported : false

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:157)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:101)
	... 7 more

**Comment by melhajj06** [comment]
I'm not sure if this will help you guys, but I was getting the same error using version 1.4.14 on Intellij IDEA 2026.2.2. Particularly, when running with `--verbose`, I found that the plugin kept forcing JUnit 5 while my project used JUnit 4. The docs say that the appropriate plugin will be detected (i.e., JUnit 4 or 5), and my version of JUnit (JUnit 4.12) was within the supported version range of PIT (JUnit 4.6+). To fix this, I simply removed `pitest-junit5-plugin-xxx.jar` from the plugin's `lib/` directory. For me, at least, this worked.
