### ISSUE TITLE
PluginException: `ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by thesn10** [mjedynak/pit-idea-plugin#63]
```java
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'pl.mjedynak.idea.plugins.pit.actions.RunSomeTestsPitAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: PIT mutation testing Idea plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by roefer** [comment]
Sorry, I don't have a pull request, but this patch fixes the issue. It basically just does, what [this post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/18697727524754-Deprecation-warning-with-ActionUpdateThread) suggests.

[pit-idea-plugin-15-23-56.patch](https://github.com/user-attachments/files/17413182/pit-idea-plugin-15-23-56.patch)
