### ISSUE TITLE
Error when running PitRunner for the first time

### ISSUE THREAD

**Issue by potmo** [mjedynak/pit-idea-plugin#7]
```
10:17:16 AM PIT >> INFO : Sending 237 test classes to slave
10:17:16 AM PIT >> INFO : Sent tests to slave
10:17:16 AM PIT >> INFO : SLAVE : 10:17:16 AM PIT >> SEVERE : Error calculating coverage. Process will exit.
java.lang.RuntimeException: Stub!
    at junit.runner.Version.id(Version.java:5)
    at org.pitest.junit.JUnitCompatibleConfiguration.verifyEnvironment(JUnitCompatibleConfiguration.java:5
10:17:16 AM PIT >> INFO : SLAVE : 9)
    at org.pitest.mutationtest.config.CompoundConfiguration$4.apply(CompoundConfiguration.java:101)
    at org.pitest.mutationtest.config.CompoundConfiguration$4.apply(CompoundConfiguration.java:99)
    at org.pitest.functional.FCollection.flatMapTo(FCollection.
10:17:16 AM PIT >> INFO : SLAVE : java:56)
    at org.pitest.functional.FCollection.flatMap(FCollection.java:66)
    at org.pitest.mutationtest.config.CompoundConfiguration.verifyEnvironment(CompoundConfiguration.java:89)
    at org.pitest.coverage.execute.CoverageSlave.main(CoverageSlave.java:64)

10:17:16 AM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.20-b23
Uptime : 3147
Input -> 
 1 : -Dvisualvm.id=4366397987742
 2 : -Didea.launcher.port=7533
 3 : -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin
 4 : -Dfile.encoding=UTF-8
BootClassPathSupported : true

    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
    at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:131)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:85)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
    at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:112)
    at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:101)
    at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
    at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:72)
    at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.20-b23
Uptime : 3147
Input -> 
 1 : -Dvisualvm.id=4366397987742
 2 : -Didea.launcher.port=7533
 3 : -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin
 4 : -Dfile.encoding=UTF-8
BootClassPathSupported : true

    at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
    at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:65)
    at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:63)
    at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:36)
    at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:267)
    at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:63)
    ... 5 more
10:17:16 AM PIT >> SEVERE : Coverage generator Slave exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation slave exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.20-b23
Uptime : 3151
Input -> 
 1 : -Dvisualvm.id=4366397987742
 2 : -Didea.launcher.port=7533
 3 : -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin
 4 : -Dfile.encoding=UTF-8
BootClassPathSupported : true


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.20-b23
Uptime : 3151
Input -> 
 1 : -Dvisualvm.id=4366397987742
 2 : -Didea.launcher.port=7533
 3 : -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin
 4 : -Dfile.encoding=UTF-8
BootClassPathSupported : true

    at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:101)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
    at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:112)
    at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:101)
    at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
    at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:72)
    at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.pitest.util.PitError: Coverage generation slave exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.20-b23
Uptime : 3151
Input -> 
 1 : -Dvisualvm.id=4366397987742
 2 : -Didea.launcher.port=7533
 3 : -Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin
 4 : -Dfile.encoding=UTF-8
BootClassPathSupported : true

    at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:135)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:85)
    ... 11 more
```

**Comment by potmo** [comment]
Im using JUnit with Mockito btw

**Comment by potmo** [comment]
btw I'm on a mac. IntelliJ 14. IU-141.914.3
I may not have set up the `Build Requirements` correctly. I'm not sure what it means by setting `build.ideaInstallationPath` etc. What should it point to?

**Comment by mjedynak** [comment]
Seems like an issue with older version of PIT, please reopen if that's not the case.
